# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFPSjV5xuXQ8S2bptOOHOp89JdXMVtFk
"""

#importing modules
import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd

#scraping data from url
url="https://www.flipkart.com/search?q=mobiles"
r=requests.get(url)


soup=BeautifulSoup(r.content,"html.parser")


titles=soup.find_all("div",class_="_4rR01T")
ratings=soup.find_all("div",class_="_3LWZlK")
reviews=soup.find_all("span",class_="_2_R_DZ")
prices=soup.find_all("div",class_="_30jeq3 _1_WHN1")

#Creating empty variables to store clean data
mt=[]
mr=[]
mre=[]
mp=[]

for title,rating,review,price in zip(titles,ratings,reviews,prices):
  #appending clean data to their respective variables
  mt.append(title.text)
  mr.append(rating.text)
  mre.append(review.text)
  mp.append(price.text)

d={'mt':mt,'mr':mr,'mre':mre,'mp':mp}
print(d)

#Converting dictionary to DataFrame by using pandas
model=pd.DataFrame(data=d)

model.to_csv("mobilesdata.csv")